name: 'Variable Substitution'
description: 'Substitutes variables in JSON files with GitHub secrets or environment variables'
inputs:
  files:
    description: 'Comma separated list of JSON files in which tokens are to be substituted. Files names must be specified relative to the folder-path with no spaces.'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Substitute workflow variables
      uses: ./src
      run: python main.py ${{ inputs.files }}
      shell: bash