name: Integration Test
on: [push]

jobs:
  build:
    environment: test
    env:
      CONFIGURATION_FILE: ./example.json,./config.json
      ACTION_ENV: production
      VISIBLE_VARIABLE: ${{ vars.VISIBLE_VARIABLE }}
      HIDDEN_SECRET_KEY: ${{ secrets.HIDDEN_SECRET_KEY }}

    runs-on: ubuntu-latest
    name: Substitutes variables and secrets
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Substitute json variables
        id: substitute
        uses: mattcollie/variable-substitution@dev
        with:
          files: ${{ env.CONFIGURATION_FILE }}