name: Test Action
on:
  push:
    branches: [ "dev" ]


jobs:
  test:
    environment: test
    env:
      CONFIGURATION_FILE: ./example.json,./test.json
      ACTION_ENV: action-test
      VISIBLE_VARIABLE: ${{ vars.VISIBLE_VARIABLE }}
      HIDDEN_SECRET_KEY: ${{ secrets.HIDDEN_SECRET_KEY }}

    runs-on: ubuntu-latest
    name: Substitutes variables and secrets
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Substitute json variables
        id: substitute
        uses: ./ # Uses an action in the root directory
        # or use a released GitHub Action
        # uses: mattcollie/variable-substitution@v1
        with:
          files: ${{ env.CONFIGURATION_FILE }}
      - name: Test JSON Variable Substitution
        run: |
          python src/test_json_substitution.py ${{ env.CONFIGURATION_FILE }}